glados/functional_tests.py
glados/static/coffee/views/Compound/CompoundNameClassificationView.coffee
glados/static/js/views/Compound/CompoundNameClassificationView.js

Travis CI Tests now work and can be used to test the app automatically!

Make travis tests work

---

glados/static/coffee/models/DocumentAssayNetwork.coffee
glados/static/coffee/views/base/DANViewExt.coffee
glados/static/js/models/DocumentAssayNetwork.js
glados/static/js/views/base/DANViewExt.js
glados/templates/glados/DocumentAssayNetwork/VisualisationBase.html

For the clustering, the algorithm used [here](https://github.com/chembl/chembl_assay_matrix/blob/master/chembl_assay_network/matrix.py#L27) should be investigated and used.

Document Assay Network: Add ordering

---

glados/static/coffee/models/CompoundTargetMatrix.coffee
glados/static/coffee/views/SearchResults/CompoundTargetMatrixView.coffee
glados/static/js/models/CompoundTargetMatrix.js
glados/static/js/views/SearchResults/CompoundTargetMatrixView.js
glados/templates/glados/Handlebars/CommonSources.html
glados/templates/glados/SearchResultsParts/CompoundTargetMatrix.html

- Row and column sorting was implemented.
- A leyend generates automatically for the cell colours
- the visualisation can be configured, (initial sorting, properties available for colouring, initial colouring.)
- Zoom and panning were implemented.

Improve Compounds vs Targets Matrix

---

src/glados/static/coffee/SearchResultsApp.coffee
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/views/SearchResults/SimilaritySearchResultsView.coffee
src/glados/templates/glados/CompoundReportCardParts/SimilarCompounds.html
src/glados/templates/glados/SimilaritySearchResultsParts/SearchResultsMain.html
src/glados/templates/glados/base/js_imports_for_all.html

It now shows the actual similarity per compound and shows the threshold used for the search.

Improve similarity results page

---

.travis.yml
requirements.txt
run_tests_no_install.sh
setup.py
src/glados/static/coffee/Settings.coffee
src/glados/tests/report_card_tester.py
src/glados/tests/test_doc_rep_card.py
src/glados/tests/test_javascript.py

travis test downgrade to firefox 44 selenium 2.52 due to unstable deployment on travis with latest releases

travis tests fixed! :)

---

src/glados/static/coffee/SearchResultsApp.coffee
src/glados/static/coffee/Settings.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/views/SearchResults/MarvinSketcherView.coffee
src/glados/templates/glados/FlexmatchSearchResultsParts/SearchResultsMain.html
src/glados/templates/glados/MainPageParts/marvin_editor.html
src/glados/templates/glados/SimilaritySearchResultsParts/SearchResultsMain.html
src/glados/templates/glados/base/PaginatedCollections/DefaultInfinityBrowserContent.html
src/glados/urls.py

The buttons were reorganised, flexmatch search button was added. Also, its results page was also implemented.

Improve Marvinjs Interface

---

src/glados/static/coffee/models/SearchModel.coffee
src/glados/static/coffee/styling/buttons_helper.coffee
src/glados/static/coffee/views/SearchResults/SearchBarView.coffee

when mobile devices show keyboard resize event is triggered, should not re-render some components if the screen type is still the same as the last render (SMALL|MEDIUM|LARGE)

fix for expandable search bar on mobile devices

---

src/glados/static/coffee/Settings.coffee
src/glados/static/coffee/models/CompoundTargetMatrix.coffee
src/glados/static/coffee/views/SearchResults/CompoundResultsGraphView.coffee
src/glados/static/coffee/views/SearchResults/CompoundTargetMatrixView.coffee
src/glados/templates/glados/SearchResultsParts/CompoundTargetMatrixBase.html

The layout of the matrix has been improved. It is still missing to improve the zoom interactions with the user. The user should be able to activate and deactivate the zoom with a button. The zoom uses the scroll of the mouse and it can cause confusion with the scroll of the page. Also, the user could zoom in and zoom out using buttons like '+' and '-'. 
We also need to review the retrieval of the information, and the data structure for the matrix. Elasticsearch can be very useful for filtering and aggregating data, reducing the amount of items to be processed.

Improve ES Results as Matrix visualisation.

---

src/glados/static/coffee/views/SearchResults/CompoundResultsGraphView.coffee
src/glados/static/coffee/views/SearchResults/CompoundTargetMatrixView.coffee

They are not shown in the plot, and they mess the axes range.

Es Results Plot: remove elements with null values for any axis

---

src/glados/static/coffee/views/SearchResults/CompoundTargetMatrixView.coffee

just after finishing rendering, the zoom and translation were being miscalculated for some reason.

ES results matrix: Fix bug with zooming.

---

src/glados/templates/glados/base/embed_base.html

adding missing semicolon

---

src/glados/static/coffee/ActivitiesBrowserApp.coffee
src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/ActivitySchema.coffee
src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee
src/glados/static/coffee/views/SearchResults/SearchBarView.coffee
src/glados/templates/glados/base/js_imports_for_all.html

There are still many issues to be fixed with the faceting and pagination.

Improve activities browser

---

src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee

inclusion of elastic search _metadata and exclusion of large denormalised id's lists from the queries

Inclusion of elastic search _metadata and 

---

src/glados/static/coffee/ActivitiesBrowserApp.coffee
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Activity/ActivityAggregation.coffee
src/glados/static/coffee/models/Activity/CompoundTargetActivitySummary.coffee
src/glados/static/coffee/models/CompoundTargetMatrix.coffee
src/glados/static/coffee/models/visualisation/PropertiesFactory.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/tests/MatrixTest.coffee
src/glados/static/coffee/views/Activity/ActivityAggregationView.coffee
src/glados/static/coffee/views/MiniReportCardView.coffee
src/glados/static/coffee/views/Visualisation/MatrixView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/static/testData/MatrixTestData0.json
src/glados/templates/glados/Handlebars/CommonSources.html
src/glados/templates/glados/base/js_imports_for_all.html

- The initial zoom is now calculated by searching for the optimal zoom (the one that minimises the empty area) 
- Columns and rows headers are now highlighted on cell hover. 
- Added a qtip for cells with cell data and a link to activities browser.

Cosmetic improvements for compound target matrix

---

src/glados/static/coffee/Settings.coffee
src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee
src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee
src/glados/static/coffee/views/SearchResults/SearchBarView.coffee
src/glados/static/coffee/views/SearchResults/SearchResultsView.coffee
src/glados/static/coffee/views/base/ResponsiviseViewExt.coffee

When the base element has changed size, it checks the size periodically until the size stopped changing. Then this happens, it renders.

Improve responsive repaint

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/FacetingHandler.coffee
src/glados/static/coffee/tests/PaginatedCollectionTest.coffee

faceting handler update to 10 intervals and big negative number

---

.travis.yml
condaEnvironment.yml
manage.py
requirements.txt
src/glados/locale/en_gb/LC_MESSAGES/django.po
src/glados/manage.py
src/glados/settings.py
src/glados/templates/glados/layoutTest.html
src/glados/templates/glados/stringStandardisationTest.html
src/glados/urls.py
src/glados/utils.py

This is going to be used to standardise the strings in chembl. This first minimal example is to make sure it is deployed correctly.

Add minimal example of django translation

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/tests/ColumnsFactoryTest.coffee

One step for: 
https://github.com/chembl/GLaDOS/issues/287

Check Compound Table Columns

---

src/glados/templates/glados/Sketchers/marvinSearch.html

Fixes https://github.com/chembl/GLaDOS/issues/280

Marvin: change search name to connectivity

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/models/Tissue.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee

one step for https://github.com/chembl/GLaDOS/issues/289

Review tissue columns

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/models/Document.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee

One step for https://github.com/chembl/GLaDOS/issues/291

Review document columns

---

src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
src/glados/static/coffee/tests/PaginatedCollectionTest.coffee

Should fix https://github.com/chembl/GLaDOS/issues/361

Paginated Col Dwnld: use id_column when requesting specific items

---

src/glados/locale/en/LC_MESSAGES/glados_es_generated.po
src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/models/paginatedCollections/esSchema/ActivitySchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/AssaySchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/CellLineSchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/CompoundSchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/DocumentSchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/FacetingHandler.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/TargetSchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/TissueSchema.coffee

Fixes for:
#287
#288
#289
#290
#291
#292
#293

Updated configuration for all filters

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/views/Browsers/BrowserToolBarView.coffee
src/glados/static/coffee/views/PaginatedViews/ColumnsHandling/ColumnsHandlerView.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee

Some sections were getting stuck in a preloader when 0 results.

Fix search results page when 0 results

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/tests/UtilsTest.coffee

This reduces significantly code repetition in the report card app. This will allow to standardise the aggregations, using the recently created ```Aggregation``` model. This is a step to achieve https://github.com/chembl/GLaDOS/issues/295

(Target Report Card) Use same function to init each section

---

src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/SearchResultsParts/SearchBar.html

Should fix https://github.com/chembl/GLaDOS/issues/382

Search Bar Style: improve css to fix white gap at left of srch btn

---

src/glados/static/coffee/SearchResultsApp.coffee
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/models/paginatedCollections/WSPaginatedCollection.coffee
src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee
src/glados/static/coffee/views/MainPage/CentralCardView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Browsers/DefaultBrowserContent.html
src/glados/templates/glados/Handlebars/CommonSources.html
src/glados/templates/glados/MainPageParts/database_schema.html
src/glados/templates/glados/MainPageParts/ws_diagram.html
src/glados/templates/glados/Sketchers/marvinSearch.html

Structure search limit increase and present real number of results while downloading

---

src/glados/static/coffee/models/paginatedCollections/ClientSidePaginatedCollection.coffee
src/glados/static/coffee/models/paginatedCollections/ColumnsHandler.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/tests/ColumnsHandlerTest.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee

This fixes the collections in the report card parts (Target components, relations, and approved drugs and clinical candidates). I will add assertions for this sections to the Ghost inspector test (https://app.ghostinspector.com/tests/59f33e36639a7d76ba1fd34e)

Fix non es paginated views

---

src/glados/static/coffee/SearchResultsApp.coffee
src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
src/glados/static/coffee/models/paginatedCollections/WSPaginatedCollection.coffee
src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Browsers/DefaultBrowserContent.html

blink page change while streaming
One Step more for #399

Structure Search: facets cover load facets on first and last call, don't

---

src/glados/static/coffee/SearchResultsApp.coffee
src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/templates/glados/Handlebars/CommonSources.html

Final step in this branch for: #399

Structure Searches: Update to fix table view while streaming

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/documentReportCardApp.coffee
src/glados/static/coffee/views/Document/DocumentAssayNetworkView.coffee
src/glados/static/coffee/views/Document/DocumentBasicInformationView.coffee
src/glados/static/coffee/views/Document/DocumentWordCloudView.coffee
src/glados/templates/glados/DocumentReportCardParts/ActivitySummary.html
src/glados/templates/glados/DocumentReportCardParts/ActivitySummaryToEmbed.html
src/glados/templates/glados/DocumentReportCardParts/AssaySummary.html
src/glados/templates/glados/DocumentReportCardParts/AssaySummaryToEmbed.html
src/glados/templates/glados/DocumentReportCardParts/CompoundSummary.html
src/glados/templates/glados/DocumentReportCardParts/CompoundSummaryToEmbed.html
src/glados/templates/glados/DocumentReportCardParts/TargetSummary.html
src/glados/templates/glados/DocumentReportCardParts/TargetSummaryToEmbed.html
src/glados/templates/glados/documentReportCard.html
src/glados/urls.py

**Important:** only 2 of the 4 new pie charts is finished. The others are still placeholders.
- For the Protein Target Summary we need chembl/GLaDOS-es#7
- For the Compound Summaries we need chembl/GLaDOS-es#8
This is another step towards #295

Add charts for document report card

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/cellLineReportCardApp.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/views/CellLine/CellLineBasicInformationView.coffee
src/glados/templates/glados/CellReportCardParts/ActivitySummary.html
src/glados/templates/glados/CellReportCardParts/ActivitySummaryToEmbed.html
src/glados/templates/glados/CellReportCardParts/AssaySummary.html
src/glados/templates/glados/CellReportCardParts/AssaySummaryToEmbed.html
src/glados/templates/glados/CellReportCardParts/CompoundSummary.html
src/glados/templates/glados/CellReportCardParts/CompoundSummaryToEmbed.html
src/glados/templates/glados/cellLineReportCard.html
src/glados/urls.py

**Important:** only 1 of the 3 new pie charts is finished. The others are still placeholders.
- For the Activity Summary we need chembl/GLaDOS-es#9
- For the Compound Summaries we need chembl/GLaDOS-es#10
This is another step towards #295

Add charts for cell report card

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/TissueReportCardApp.coffee
src/glados/templates/glados/TissueReportCardParts/ActivitySummary.html
src/glados/templates/glados/TissueReportCardParts/ActivitySummaryToEmbed.html
src/glados/templates/glados/TissueReportCardParts/AssaySummary.html
src/glados/templates/glados/TissueReportCardParts/AssaySummaryToEmbed.html
src/glados/templates/glados/TissueReportCardParts/CompoundSummary.html
src/glados/templates/glados/TissueReportCardParts/CompoundSummaryToEmbed.html
src/glados/templates/glados/base/js_imports_for_all.html
src/glados/templates/glados/tissueReportCard.html
src/glados/urls.py

**Important:** only 1 of the 3 new pie charts is finished. The others are still placeholders.
- For the Activity Summary we need chembl/GLaDOS-es#11
- For the Compound Summaries we need chembl/GLaDOS-es#12
This is another step towards #295

Add charts to tissue report card

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/models/ApprovedDrugClinicalCandidate.coffee
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/models/base/ReportCardEntity.coffee
src/glados/static/coffee/models/paginatedCollections/ClientSidePaginatedCollection.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee
src/glados/static/coffee/views/PaginatedViews/PaginationFunctions.coffee
src/glados/static/coffee/views/Target/ApprovedDrugsClinicalCandidatesView.coffee
src/glados/templates/glados/Handlebars/CommonSources.html
src/glados/templates/glados/base/js_imports_for_all.html

This should fix https://github.com/chembl/GLaDOS/issues/117

Fix approved drugs clinical candidates links

---

src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/tests/ApprovedDrugClinicalCandidateListTest.coffee

This should fix https://github.com/chembl/GLaDOS/issues/117 for real.

AppDrugsClinicalCands: do not assume both lists are in same order.

---

src/glados/static/coffee/models/Activity/ActivityAggregationMatrix.coffee
src/glados/static/coffee/views/Visualisation/MatrixView.coffee

This should fix https://github.com/chembl/GLaDOS/issues/332

Activity Matrix: fix bug with grid rectangles overlapping elements

---

src/glados/static/coffee/models/Activity/ActivityAggregationMatrix.coffee
src/glados/static/coffee/tests/MatrixTest.coffee
src/glados/static/coffee/views/Visualisation/MatrixView.coffee
src/glados/static/scss/chembl-style.scss

This should fix https://github.com/chembl/GLaDOS/issues/334 and https://github.com/chembl/GLaDOS/issues/333

Activity Matrix: add links for cols/rows headers/footers

---

src/glados/static/coffee/views/Compound/CompoundNameClassificationView.coffee
src/glados/templates/glados/CompoundReportCardParts/NameAndClassification.html

This should close https://github.com/chembl/GLaDOS/issues/255

Compound Name And Classification: update max phase descriptions

---

src/glados/static/coffee/views/Visualisation/MatrixView.coffee
src/glados/static/scss/chembl-style.scss

https://github.com/chembl/GLaDOS/issues/446

Matrix View: show grabbing cursor over cells when grab is activated

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/models/Assay.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/AssaySchema.coffee
src/glados/static/coffee/tests/DownloadsTest.coffee
src/glados/static/coffee/tests/TestsUtils.coffee

This should close once and for all #290

Assay: set up default column/filter config as discussed in #290

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/models/Document.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/DocumentSchema.coffee
src/glados/static/coffee/tests/DownloadsTest.coffee

This should close once and for all #291

Document: add missing columns/ filters for #291

---

src/glados/static/coffee/views/SearchResults/ESResultsBioactivitySummaryView.coffee
src/glados/static/coffee/views/Visualisation/MatrixView.coffee
src/glados/templates/glados/ActivityAggregations/ActivityAggregationMatrixBase.html
src/glados/templates/glados/Handlebars/CommonSources.html

Missing commit for https://github.com/chembl/GLaDOS/pull/464

Bioactivity summary view: remove link to full screen

---

src/glados/static/coffee/TissueReportCardApp.coffee
src/glados/static/coffee/assayReportCardApp.coffee
src/glados/static/coffee/cellLineReportCardApp.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/documentReportCardApp.coffee
src/glados/static/coffee/models/Assay.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/tests/DownloadsTest.coffee
src/glados/static/coffee/views/CellLine/CellLineBasicInformationView.coffee
src/glados/static/coffee/views/Tissue/TissueBasicInformationView.coffee
src/glados/templates/glados/TissueReportCardParts/BasicInformation.html
src/glados/templates/glados/base/js_imports_for_all.html
src/glados/templates/glados/tissueReportCard.html

One step towards https://github.com/chembl/GLaDOS/issues/295

Update report card charts

---

src/glados/templates/glados/TissueReportCardParts/BasicInformationToEmbed.html
src/glados/urls.py

Add changes that I forgot to add in https://github.com/chembl/GLaDOS/pull/475

Add forgotten changes to mage Tissue basic information embeddable

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/TissueReportCardApp.coffee
src/glados/static/coffee/apps/Cell/CellsBrowserApp.coffee
src/glados/static/coffee/apps/Document/DocumentsBrowserApp.coffee
src/glados/static/coffee/apps/Tissue/TissuesBrowserApp.coffee
src/glados/static/coffee/assayReportCardApp.coffee
src/glados/static/coffee/cellLineReportCardApp.coffee
src/glados/static/coffee/documentReportCardApp.coffee
src/glados/static/coffee/models/Assay.coffee
src/glados/static/coffee/models/CellLine.coffee
src/glados/static/coffee/models/Document.coffee
src/glados/static/coffee/models/Tissue.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/tests/DownloadsTest.coffee
src/glados/static/coffee/views/Visualisation/PieView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Browsers/browseCells.html
src/glados/templates/glados/Browsers/browseDocuments.html
src/glados/templates/glados/Browsers/browseTissues.html
src/glados/templates/glados/base/js_imports_for_all.html
src/glados/urls.py

Add Histograms as requested in https://github.com/chembl/GLaDOS/issues/344

Add table histograms

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee

This should fix https://github.com/chembl/GLaDOS/issues/460

Fix Filters Ellipsis

---

src/glados/static/coffee/models/Activity.coffee
src/glados/static/coffee/tests/Activity/ActivityTest.coffee
src/glados/static/testData/Activity/Images/activityWithAntibodyCompESResponse.json
src/glados/static/testData/Activity/Images/activityWithEnzymeCompESResponse.json
src/glados/static/testData/Activity/Images/activityWithMetalContainingCompESResponse.json
src/glados/static/testData/Activity/Images/activityWithNaturalProductImageESResponse.json
src/glados/static/testData/Activity/Images/activityWithNormalImageSampleESResponse.json
src/glados/static/testData/Activity/Images/activityWithOligosaccharideCompESResponse.json
src/glados/static/testData/Activity/Images/activityWithPepetideCompESResponse.json
src/glados/static/testData/Activity/Images/activityWithSmallMolCompESResponse.json
src/glados/static/testData/Activity/Images/activityWithSmallMolPolymerCompESResponse.json
src/glados/templates/glados/jsTests.html

This should fix https://github.com/chembl/GLaDOS/issues/469

Fix activities special images

---

src/glados/static/coffee/views/Visualisation/MatrixView.coffee
src/glados/static/scss/chembl-style.scss

Add rows sorting label to matrix view

---

src/glados/static/coffee/models/paginatedCollections/esSchema/ActivitySchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/AssaySchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/CellLineSchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/CompoundSchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/DocumentSchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/FacetingHandler.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/TargetSchema.coffee

updates to allow custom number of categories in facets

---

src/glados/static/coffee/views/Visualisation/MatrixView.coffee

This should fix https://github.com/chembl/GLaDOS/issues/335

Fix matrix ellipsis

---

src/glados/locale/en/LC_MESSAGES/glados_es_override.po
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Aggregations/Aggregation.coffee
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/models/Document.coffee
src/glados/static/coffee/tests/UtilsTest.coffee
src/glados/static/coffee/views/ReportCards/EntityDetailsInCardView.coffee
src/glados/templates/glados/CompoundReportCardParts/Sources.html
src/glados/templates/glados/CompoundReportCardParts/SourcesToEmbed.html
src/glados/templates/glados/base/js_imports_for_all.html
src/glados/templates/glados/compoundReportCard.html
src/glados/urls.py

This should close https://github.com/chembl/GLaDOS/issues/336

Add compound sources section

---

src/glados/static/coffee/models/SearchModel.coffee

Autocomplete: group suggestions and include multiple entity links

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Compound/StructuralAlert.coffee
src/glados/static/coffee/models/Compound/StructuralAlertSet.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/tests/Compound/StructuralAlertsListTest.coffee
src/glados/static/coffee/views/PaginatedViews/Carousel.coffee
src/glados/static/coffee/views/PaginatedViews/InfiniteCards.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedCards.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee
src/glados/static/coffee/views/PaginatedViews/PaginationFunctions.coffee
src/glados/static/coffee/views/ReportCards/CarouselInCardView.coffee
src/glados/static/coffee/views/ReportCards/PaginatedTableInCardView.coffee
src/glados/static/testData/Compounds/StructuralAlerts/sampleDataToParseCHEMBL457419.json
src/glados/templates/glados/CompoundReportCardParts/StructuralAlerts.html
src/glados/templates/glados/CompoundReportCardParts/StructuralAlertsToEmbed.html
src/glados/templates/glados/Handlebars/CommonSources.html
src/glados/templates/glados/base/js_imports_for_all.html
src/glados/templates/glados/compoundReportCard.html
src/glados/templates/glados/jsTests.html
src/glados/urls.py

This should resolve https://github.com/chembl/GLaDOS/issues/301

Add compound structural alerts

---

src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/CompoundReportCardParts/WithdrawnInformation.html
src/glados/templates/glados/base/basic_table_card.html

https://github.com/chembl/GLaDOS/issues/492#issuecomment-350779469

Add withdrawal information

---

src/glados/static/coffee/models/paginatedCollections/esSchema/ActivitySchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/FacetingHandler.coffee

support to accept report_card_model configuration in facets

---

src/glados/static/coffee/ReportCardApp.coffee
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Assay.coffee
src/glados/static/coffee/models/CellLine.coffee
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/models/Document.coffee
src/glados/static/coffee/models/Target.coffee
src/glados/static/coffee/models/Tissue.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/ActivitySchema.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/FacetingHandler.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee
src/glados/static/coffee/views/PaginatedViews/ItemCardView.coffee
src/glados/static/coffee/views/Visualisation/MatrixView.coffee
src/glados/static/coffee/views/Visualisation/PlotView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Handlebars/CommonSources.html

This should close https://github.com/chembl/GLaDOS/issues/412

Show mini report cards on filters hover

---

src/glados/static/coffee/models/Activity/ActivityAggregationMatrix.coffee
src/glados/static/coffee/tests/MatrixTest.coffee
src/glados/static/coffee/views/Visualisation/MatrixView.coffee
src/glados/static/scss/chembl-style.scss

One step towards https://github.com/chembl/GLaDOS/issues/467, there are still some issues link the  url length and elastic query limitations.

Add matrix link to all columns

---

src/glados/templates/glados/cellLineReportCard.html
src/glados/templates/glados/compoundReportCard.html
src/glados/templates/glados/documentReportCard.html
src/glados/templates/glados/targetReportCard.html
src/glados/templates/glados/tissueReportCard.html

this should resolve https://github.com/chembl/GLaDOS/issues/528

Improve piecharts layout

---

src/glados/templates/glados/assayReportCard.html
src/glados/templates/glados/compoundReportCard.html
src/glados/templates/glados/documentReportCard.html

For https://github.com/chembl/GLaDOS/issues/528

Piechart report cards layout

---

src/glados/static/coffee/Settings.coffee
src/glados/static/coffee/TissueReportCardApp.coffee
src/glados/static/coffee/assayReportCardApp.coffee
src/glados/static/coffee/cellLineReportCardApp.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/documentReportCardApp.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/views/Visualisation/PieView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Handlebars/CommonSources.html
src/glados/templates/glados/assayReportCard.html
src/glados/templates/glados/base/Visualisation/DefaultPieChartContent.html
src/glados/templates/glados/base/basic_table_card.html
src/glados/templates/glados/cellLineReportCard.html
src/glados/templates/glados/compoundReportCard.html
src/glados/templates/glados/documentReportCard.html
src/glados/templates/glados/targetReportCard.html
src/glados/templates/glados/tissueReportCard.html

Attend to the comments [here](https://github.com/chembl/GLaDOS/issues/528#issuecomment-359889679)

Improve piecharts layout 2

---

src/glados/templates/glados/Handlebars/CommonSources.html

This solves  https://github.com/chembl/GLaDOS/issues/557

Center searching filters title

---

src/glados/templates/glados/Handlebars/CommonSources.html

Revert "Center searching filters title"

---

src/glados/templates/glados/Handlebars/CommonSources.html

Center loading filter message

---

src/glados/static/coffee/views/Target/TargetNameAndClassificationView.coffee

This solves https://github.com/chembl/GLaDOS/issues/487

Make target synonyms list unique on target report card

---

.travis.yml
requirements.txt
src/glados/static/coffee/Settings.coffee
src/glados/static/coffee/models/base/DownloadModelOrCollectionExt.coffee
src/glados/static/coffee/views/Compound/Compound3DMethodSelectorView.coffee
src/glados/static/coffee/views/Compound/CompoundRepresentationsView.coffee
src/glados/templates/glados/jsTests.html
src/glados/tests/report_card_tester.py
src/glados/tests/run_tests.py
src/glados/tests/test_javascript.py

Travis tests fix

---

src/glados/settings.py
src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/models/MainPage/Tweet.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/tests/MainPage/TweetsTest.coffee
src/glados/static/coffee/views/PaginatedViews/InfiniteCards.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee
src/glados/static/scss/chembl-style.scss
src/glados/static/testData/MainPage/Tweets/sampleDataToParse.json
src/glados/templates/glados/Handlebars/CommonSources.html
src/glados/templates/glados/MainPageParts/tweets.html
src/glados/templates/glados/base/PaginatedCollections/DefaultInfinityBrowserContent.html
src/glados/templates/glados/base/infinite_browse_loaders.html
src/glados/templates/glados/base/js_imports_for_all.html
src/glados/templates/glados/jsTests.html
src/glados/urls.py
src/glados/views.py

tweets with infinite view

---

src/glados/views.py

Fix usage of tweets cache

---

src/glados/templates/glados/base/embed_base.html

Hotjar Embed Fix: removal of hotjar on embedded pages

---

src/glados/static/coffee/views/Compound/MetabolismView.coffee
src/glados/static/coffee/views/Document/DocumentWordCloudView.coffee
src/glados/static/coffee/views/Target/BrowseTargetAsCirclesView.coffee
src/glados/static/coffee/views/Visualisation/HistogramView.coffee
src/glados/static/scss/chembl-style.scss

Colour palette 2

---

src/glados/static/coffee/ReportCardApp.coffee
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/documentReportCardApp.coffee
src/glados/static/coffee/models/CellLine.coffee
src/glados/static/coffee/models/Tissue.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Handlebars/CommonSources.html

chembl id lookup and redirect

---

src/glados/static/scss/chembl-style.scss
src/glados/static_files_compiler.py
src/glados/tests/test_static_files_compilation.py

chembl id lookup redirect

---

src/glados/static/coffee/Utils.coffee
src/glados/templates/glados/Handlebars/CommonSources.html
src/glados/templates/glados/base/base_layout.html

chembl id lookup redirect / missing html code

---

src/glados/templates/glados/Handlebars/CommonSources.html

Replace object with correct links

---

src/glados/static/coffee/Settings.coffee
src/glados/static/coffee/models/Compound/TargetPrediction.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/templates/glados/CompoundReportCardParts/TargetPredictions.html
src/glados/templates/glados/Handlebars/TableSources.html

finish https://github.com/chembl/GLaDOS/pull/586

Finish target predictions

---

src/glados/static/coffee/models/Compound.coffee

SMILES Sanitization: fix for miss aligned molecules and new parameter for similarity and substructure highlight

---

src/glados/static/coffee/views/base/CardView.coffee
src/glados/templates/glados/compoundReportCard.html

fix https://github.com/chembl/GLaDOS/issues/601

Compound Report Card: only show indications and clin data if data

---

src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/SearchResultsParts/SearchBarChEMBLHeader.html

Reduce height of search results that are empty

---

src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/base/left_menu_links.html

Removed SARfaris, Malaria data and DrugEBIlity links. Added link urls for Web services and ChEMBL-NTD

Remove items from left hand menu

---

src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee
src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee
src/glados/static/scss/chembl-style.scss

But add them again when they exist

Remove facet and preloader items when there are no results 

---

src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/MainPageParts/database_info.html
src/glados/templates/glados/base/base_layout.html
src/glados/templates/glados/base/breadcrumb.html
src/glados/templates/glados/mainPage.html

Add links for EBI breadcrumbs and to database summary section

---

src/glados/templates/glados/mainGlados.html

add missing commit in https://github.com/chembl/GLaDOS/pull/650

Remove duplicate breadcrumb in main page

---

src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Handlebars/MainPage/AuxiliarySources.html
src/glados/templates/glados/base/chembl_header.html
src/glados/templates/glados/base/footer.html

Reduce margin on search banner

---

src/glados/static/coffee/compoundReportCardApp.coffee

Remove compound name from Literature section in Compound report card

---

src/glados/static/coffee/models/base/Breadcrumb.coffee

Beautify breadcrumbs

---

src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/views/PaginatedViews/Carousel.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedCards.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewFactory.coffee
src/glados/static/coffee/views/ReportCards/CarouselInCardView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Handlebars/CardSources.html

Add side chevrons for report card carousels and increase number of cards in Similar compounds

---

src/glados/templates/glados/Handlebars/CardSources.html

I removed them while adding the side navigation and forgot to add them back

Add search results to carrousel view

---

src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/views/ReportCards/EntityDetailsInCardView.coffee

Sort sources in compound report card by alphabetical order

---

src/glados/settings.py
src/glados/static/coffee/TissueReportCardApp.coffee
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/apps/BreadcrumbApp.coffee
src/glados/static/coffee/apps/Main/MainGladosApp.coffee
src/glados/static/coffee/assayReportCardApp.coffee
src/glados/static/coffee/cellLineReportCardApp.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/documentReportCardApp.coffee
src/glados/static/coffee/helpers/buttons_helper.coffee
src/glados/static/coffee/models/Breadcrumb/BreadcrumbModel.coffee
src/glados/static/coffee/models/CellLine.coffee
src/glados/static/coffee/models/Tissue.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/views/Breadcrumb/BreadcrumbsView.coffee
src/glados/static/coffee/views/base/BreadcrumbsView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Handlebars/BreadcrumbSources.html
src/glados/templates/glados/base/base_layout.html
src/glados/templates/glados/base/breadcrumb.html
src/glados/templates/glados/base/js_imports_for_all.html

this should finish https://github.com/chembl/GLaDOS/issues/314

Finish breadcrumbs

---

src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee

This should fix https://github.com/chembl/GLaDOS/issues/655

Fix filters collapsed on page load

---

src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/templates/glados/Handlebars/CardSources.html

Fix bug created in structural alerts when making  #530

Structural alerts do not use custom template anymore

---

src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/base/base_layout.html
src/glados/templates/glados/mainGlados.html

Fix footer z-index for main-page and other pages

---

src/glados/static/coffee/compoundReportCardApp.coffee

Change Alternate Forms label and text to 'Alternative Forms'

---

src/glados/static/coffee/views/Compound/CompoundNameClassificationView.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/CompoundReportCardParts/NameAndClassification.html

Add withdrawal alert on compound report card summary

---

src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/SearchResultsParts/SearchBarChEMBLHeader.html
src/glados/templates/glados/base/chembl_header.html

Add beta icon to all headers 

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/models/visualisation/PropertiesFactory.coffee
src/glados/static/coffee/views/Visualisation/PieView.coffee

This changes the donut chart in main page to use 'Disease' field instead of 'Indication class'

Change aggregation in donut chart from 'Indication Class' to 'Disease'

---

src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Handlebars/TableSources.html

Change scroll trigger to table header and fix bug with table header selection

---

src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee
src/glados/static/coffee/views/PaginatedViews/ColumnsHandling/ColumnsHandlerView.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/Browsers/DefaultBrowserContent.html
src/glados/templates/glados/Handlebars/CommonSources.html

Create modal in modal specific container

---

src/glados/static/coffee/views/Browsers/BrowserFacetView.coffee
src/glados/static/coffee/views/PaginatedViews/ColumnsHandling/ColumnsHandlerView.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee

Hide 'select All' container when disabled

---

src/glados/static/coffee/ReportCardApp.coffee
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/ScrollSpy/ScrollSpyHandler.coffee
src/glados/static/coffee/views/ReportCards/ReferencesInCardView.coffee
src/glados/static/coffee/views/ScrollSpy/ScrollSpyView.coffee
src/glados/templates/glados/compoundReportCard.html

Show section in scrollspy after it has been shown in page

---

src/glados/templates/glados/Handlebars/CommonSources.html

fix https://github.com/chembl/GLaDOS/issues/732

Pie Charts: make external title link open in new tab

---

src/glados/static/scss/chembl-style.scss
src/glados/templates/glados/base/base_layout.html
src/glados/templates/glados/mainGlados.html
src/glados/templates/glados/main_page.html
src/glados/urls.py
src/glados/views.py

Small Fixes

---

src/glados/static/scss/main_page_style.scss
src/glados/templates/glados/main_page.html

Fix container class width

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/views/ReportCards/EntityDetailsInCardView.coffee
src/glados/templates/glados/CompoundReportCardParts/Sources.html

Another step for https://github.com/chembl/GLaDOS/issues/647

Add parent salt logic to compound sources

---

src/glados/static/coffee/models/Document.coffee
src/glados/static/coffee/views/MainPage/DatabaseSummaryView.coffee
src/glados/templates/glados/Handlebars/MainPage/AuxiliarySources.html
src/glados/urls.py
src/glados/views.py

Get number of deposited datasets form ES

---

src/glados/static/scss/main_page_style.scss

I did a fast check of the main page in different browsers and fixed the bugs I found. But I should do this again and with more detail after finishing all sections of the page

Fix layout in different browsers

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/views/MainPage/BrowseEntitiesAsCirclesView.coffee
src/glados/templates/glados/MainPageParts/main_carousel.html

Small browse entities fixes

---

src/glados/static/coffee/views/MainPage/BrowseEntitiesAsCirclesView.coffee

Update colour in 'Entities browser'

---

src/glados/static/coffee/views/MainPage/BrowseEntitiesAsCirclesView.coffee

Set colour by key on entities list

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/scss/splash-screen-style.scss
src/glados/templates/glados/acknowledgements.html
src/glados/templates/glados/base/base_layout.html
src/glados/templates/glados/database_schema.html
src/glados/templates/glados/faqs.html

Fix splash screen bug

---

src/glados/static/coffee/models/Compound/Metabolism.coffee
src/glados/static/coffee/tests/Compound/MetabolismTest.coffee
src/glados/static/coffee/views/Compound/CompoundMetabolismFSView.coffee

one step for https://github.com/chembl/GLaDOS/issues/647

Fix metabolism url

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/models/Document.coffee

Finish https://github.com/chembl/GLaDOS/issues/600

Finish related documents section

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/models/TargetHierarchyTree.coffee
src/glados/static/coffee/targetBrowserApp.coffee
src/glados/static/coffee/views/MainPage/BrowseEntitiesAsCirclesView.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee
src/glados/static/coffee/views/Target/BrowseTargetAsCirclesView.coffee
src/glados/templates/glados/MainPageParts/main_carousel.html

Change target browser to aggregation

---

src/glados/static/coffee/views/Assay/AssayBasicInformationView.coffee
src/glados/templates/glados/AssayReportCardParts/BasicInformation.html

Fix https://github.com/chembl/GLaDOS/issues/715

Assay report card: fix assay reference in basic information

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/templates/glados/Handlebars/ColumnsSource.html

This should fix https://github.com/chembl/GLaDOS/issues/584

Use elasticsearch for alternate forms

---

src/glados/static/scss/header_style.scss
src/glados/templates/glados/Handlebars/MainPage/AuxiliarySources.html

Display license information on database summary section

---

src/glados/static/coffee/models/Target.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/views/References/ReferencesView.coffee
src/glados/templates/glados/Handlebars/CommonSources.html

This should be the last step for https://github.com/chembl/GLaDOS/issues/508

Include target component refs in target xrefs

---

src/glados/static/coffee/views/Target/BrowseTargetAsCirclesView.coffee
src/glados/static/scss/main_page_style.scss
src/glados/templates/glados/Handlebars/MainPage/AuxiliarySources.html
src/glados/templates/glados/Handlebars/MainPage/VisualisationSources.html
src/glados/templates/glados/MainPageParts/associated_resources.html
src/glados/templates/glados/MainPageParts/explore_the_database.html
src/glados/templates/glados/MainPageParts/want_to_know_more.html
src/glados/templates/glados/main_page.html

Small fixes for a few bugs and responsive layout

---

src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/views/Compound/CompoundNameClassificationView.coffee
src/glados/templates/glados/CompoundReportCardParts/ClinicalData.html
src/glados/templates/glados/CompoundReportCardParts/NameAndClassification.html

One step towards https://github.com/chembl/GLaDOS/issues/647

Improve clinical data links

---

src/glados/static/coffee/models/Compound.coffee

One small detail for clinical data links (https://github.com/chembl/GLaDOS/issues/647)

Compound clinical data link: truncate terms text to 100 chars

---

src/glados/static/scss/chembl-style.scss

One step for https://github.com/chembl/GLaDOS/issues/790

Molecule features: make second row colour more bluish

---

src/glados/static/scss/main_page_style.scss
src/glados/templates/glados/MainPageParts/about_chembl.html
src/glados/templates/glados/base/chembl_header.html

Add web services button to header and main page

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/apps/Embedding/EmbeddingApp.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Aggregations/Aggregation.coffee
src/glados/static/coffee/models/visualisation/PropertiesFactory.coffee
src/glados/static/coffee/views/Visualisation/HistogramView.coffee
src/glados/static/coffee/views/Visualisation/LegendView.coffee
src/glados/static/coffee/views/Visualisation/PieView.coffee
src/glados/templates/glados/MainPageParts/associated_resources.html

Change main page histogram data

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/targetBrowserApp.coffee
src/glados/static/coffee/views/MainPage/ZoomableSunburstView.coffee
src/glados/static/coffee/views/Target/BrowseTargetAsCirclesView.coffee
src/glados/static/scss/main_page_style.scss
src/glados/templates/glados/MainPageParts/Visualizations/MaxPhaseForDiseaseDonut.html
src/glados/templates/glados/MainPageParts/Visualizations/zoomable_sunburst.html
src/glados/templates/glados/MainPageParts/main_carousel.html
src/glados/templates/glados/base/js_imports_for_all.html

Zoomable sunburst

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/views/Target/BrowseTargetAsCirclesView.coffee
src/glados/static/coffee/views/Visualisation/LegendView.coffee
src/glados/templates/glados/MainPageParts/explore_the_database.html
src/glados/templates/glados/MainPageParts/main_carousel.html

Change bubble chart aggregation

---

src/glados/static/coffee/views/Target/BrowseTargetAsCirclesView.coffee

Fix zoom bug

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/visualisation/PropertiesFactory.coffee
src/glados/static/coffee/views/Visualisation/HistogramView.coffee
src/glados/templates/glados/MainPageParts/Visualizations/first_approval_histogram.html
src/glados/templates/glados/MainPageParts/explore_the_database.html
src/glados/templates/glados/MainPageParts/main_carousel.html

First approval vs percentage histogram

---

src/glados/templates/glados/base/base_layout.html
src/glados/templates/glados/base/data_protection_banner.html
src/glados/templates/glados/base/hotjar_analytics.html

For https://github.com/chembl/GLaDOS/issues/799

Add data protection banner

---

requirements.txt
src/glados/templates/glados/CompoundReportCardParts/3DViewModal.html
src/glados/urls.py

We are still not ready for django 2.0, but we should have the latest one just before django 2.

Upgrade django to 1.9.13

---

src/glados/static/scss/chembl-style.scss

Change molecule features icons colors

---

src/glados/static/coffee/apps/VisualisePageApp.coffee
src/glados/static/coffee/views/MainPage/ZoomableSunburstView.coffee
src/glados/static/coffee/views/Target/BrowseTargetAsCirclesView.coffee
src/glados/static/scss/visualisations_style.scss
src/glados/templates/glados/visualise.html

Visualisations page

---

src/glados/static/coffee/compoundReportCardApp.coffee

Fixes this:
on https://chembl-glados.herokuapp.com/g/#browse/compounds

Fix bioactivities-of-compound histogram

---

src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Compound/MechanismOfAction.coffee
src/glados/static/coffee/models/paginatedCollections/SpecificFlavours/MechanismsOfActionList.coffee
src/glados/static/coffee/tests/Compound/MechanismsOfActionTest.coffee
src/glados/static/coffee/views/ReportCards/PaginatedTableInCardView.coffee

Final details to finish mechanisms of action task in https://github.com/chembl/GLaDOS/issues/647

Add parent salt logic to mechanisms of action (show only if approved drug)

---

src/glados/static/coffee/helpers/buttons_helper.coffee
src/glados/static/coffee/models/SearchModel.coffee
src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionBase.coffee
src/glados/static/coffee/routers/MainGladosRouter.coffee
src/glados/static/coffee/tests/PaginatedCollections/ESPaginatedCollections/FetchingStateTests.coffee
src/glados/static/coffee/tests/PaginatedCollections/ESPaginatedCollections/SearchingStateTests.coffee
src/glados/static/coffee/tests/PaginatedCollections/ESPaginatedCollections/SleepAwakeTests.coffee
src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee
src/glados/static/coffee/views/SearchResults/SearchBarView.coffee
src/glados/static/coffee/views/SearchResults/SearchResultsView.coffee
src/glados/templates/glados/Handlebars/SearchResults/AuxiliarySources.html
src/glados/templates/glados/Handlebars/SearchResults/SearchResultsSources.html
src/glados/templates/glados/jsTests.html

This should fix the bug described in https://github.com/chembl/GLaDOS/issues/849, which was caused by https://github.com/chembl/GLaDOS/pull/848. 
This also does the final step to really increase the search speed (https://github.com/chembl/GLaDOS/issues/656)

Fix search results bug

---

src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee

another fix for https://github.com/chembl/GLaDOS/issues/849

BrowserMenuView: do not check if element is visible, not necessary

---

src/glados/static/scss/_chembl_base.scss
src/glados/static/scss/design_components_style.scss
src/glados/templates/glados/base/design_components.html

Design components page descriptions

---

src/glados/templates/glados/base/design_components.html

Finish adding codes and names to colours

---

src/glados/templates/glados/Handlebars/MainPage/VisualisationSources.html
src/glados/templates/glados/visualise.html

So the urls are always correct independently of the environment or server.

Use url: django url tag in visualisations page

---

src/glados/templates/glados/base/chembl_header.html
src/glados/urls.py
src/glados/views.py

for https://github.com/chembl/GLaDOS/issues/869

Update faq acks dwnloads links

---

src/glados/static/coffee/Settings.coffee
src/glados/static/coffee/views/Breadcrumb/BreadcrumbsView.coffee

for https://github.com/chembl/GLaDOS/issues/877

Tiny urls generator: allow to indicate absolute url in template

---

src/glados/static/coffee/apps/BreadcrumbApp.coffee
src/glados/static/coffee/apps/Main/MainGladosApp.coffee
src/glados/static/coffee/helpers/buttons_helper.coffee
src/glados/static/coffee/routers/MainGladosRouter.coffee
src/glados/static/coffee/views/Breadcrumb/BreadcrumbsView.coffee
src/glados/static/scss/report_card_style.scss
src/glados/templates/glados/Handlebars/BreadcrumbSources.html
src/glados/templates/glados/Handlebars/CroppedContainers.html

For https://github.com/chembl/GLaDOS/issues/883 and https://github.com/chembl/GLaDOS/issues/699

Make share modal more user friendly

---

src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionBase.coffee
src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee
src/glados/static/coffee/views/SearchResults/ESResultsBioactivitySummaryView.coffee
src/glados/static/coffee/views/SearchResults/ESResultsGraphView.coffee
src/glados/static/coffee/views/Visualisation/PlotView.coffee

For https://github.com/chembl/GLaDOS/issues/888

Fix scatter plot menu and heatmap results view

---

src/glados/static/coffee/Utils.coffee

For https://github.com/chembl/GLaDOS/issues/853

shortenLinkIfTooLongAndOpen: assume url is ready after shortening

---

src/glados/templates/glados/base/base_layout.html

hide splash screen on DOM Load and not use glados function

---

src/glados/static/coffee/models/SearchModel.coffee

Autocomplete Fix: limit autocomplete to text under 75 chars and

---

src/glados/static/coffee/MainPageApp.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/templates/glados/MainPageParts/explore_the_database.html
src/glados/templates/glados/MainPageParts/main_carousel.html

Fix molecule type by approval graph

---

src/glados/static/coffee/models/Activity.coffee
src/glados/static/coffee/tests/DownloadsTest.coffee

for https://github.com/chembl/GLaDOS/issues/921

Add target type to activities browser

---

src/glados/static/coffee/models/paginatedCollections/esSchema/TargetSchema.coffee
src/glados/static/coffee/views/PaginatedViews/ColumnsHandling/ColumnsHandlerView.coffee
src/glados/templates/glados/Handlebars/CommonSources.html

Add protein target classification l3 l4 to targets browser

---

src/glados/static/coffee/apps/Browsers/BrowserApp.coffee
src/glados/static/coffee/apps/Main/MainGladosApp.coffee
src/glados/static/coffee/routers/MainGladosRouter.coffee

Allow state objects in entity browsers urls

---

src/glados/static/coffee/SearchResultsApp.coffee
src/glados/static/coffee/apps/Browsers/BrowserApp.coffee
src/glados/static/coffee/helpers/URLHelper.coffee
src/glados/static/coffee/models/SearchModel.coffee
src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/StateSaving/ESCollectionStateSavingFunctions.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/FacetingHandler.coffee
src/glados/static/coffee/routers/MainGladosRouter.coffee
src/glados/static/coffee/tests/DynamicURLs/URLHelperTests.coffee
src/glados/static/coffee/tests/PaginatedCollections/ESPaginatedCollections/FetchingStateTests.coffee
src/glados/static/coffee/tests/PaginatedCollections/ESPaginatedCollections/StateChangesEvents.coffee
src/glados/static/coffee/views/Breadcrumb/BreadcrumbsView.coffee

Probably the final step for #839

Update url after change in es query

---

src/glados/templates/glados/Handlebars/Browsers/QueryEditorSources.html
src/glados/urls.py

Query Editor: add links to FAQs in gitbook.

---

src/glados/static/coffee/models/TargetRelation.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/SpecificFlavours/TargetRelationsList.coffee
src/glados/templates/glados/base/js_imports_for_all.html

This should fix https://github.com/chembl/GLaDOS/issues/975

Fix target relations links

---

src/glados/static/coffee/models/paginatedCollections/Settings.coffee

closes https://github.com/chembl/GLaDOS/issues/989

Turn off structure highlighting and similarity maps by default

---

src/glados/glados_server_statistics.py
src/glados/heatmap_helper.py
src/glados/views.py

This is also useful to test the configuration of the in-progress dynamic downloads.

Server statistics: create a separate file to handle its functions.

---

src/glados/dynamic_downloads_manager.py
src/glados/manage.py
src/glados/settings.py

@chembl-bot try to test this one

Downloads: tweak timeouts and scroll parameters

---

src/glados/static/coffee/models/SearchModel.coffee
src/glados/static/coffee/tests/LegendTest.coffee
src/glados/static/coffee/tests/Search/AutoSuggestionTests.coffee
src/glados/static/coffee/views/SearchResults/SearchBarAutocompleteView.coffee
src/glados/static/scss/search_results_style.scss
src/glados/templates/glados/SearchResultsParts/SearchBarAutocomplete.html
src/glados/templates/glados/jsTests.html

This is for https://github.com/chembl/GLaDOS/issues/1019

Add autosuggest preloader

---

src/glados/dynamic_downloads_manager.py

This should finish https://github.com/chembl/GLaDOS/issues/1011

Improve downloads parsing functions

---

src/glados/urls.py

One step for https://github.com/chembl/GLaDOS/issues/1048

URL: create redirection for old report card urls

---

src/glados/static/coffee/models/Compound/Drug.coffee
src/glados/static/coffee/tests/DownloadsTest.coffee

This is to address https://github.com/chembl/GLaDOS/issues/787#issuecomment-472024079

Drugs: add withdrawn class to additional columns and download columns

---

src/glados/api/dynamic-downloads/columns_parser.py
src/glados/api/dynamic-downloads/downloads_manager.py
src/glados/static/coffee/models/Compound/DrugIndication.coffee
src/glados/static/coffee/models/Compound/MechanismOfAction.coffee

Should finish https://github.com/chembl/GLaDOS/issues/954 and https://github.com/chembl/GLaDOS/issues/953

Fix drug indications mechanisms of action downloads

---

src/glados/static/coffee/helpers/URLHelper.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee

Should fix https://github.com/chembl/GLaDOS/issues/986

State URLs: restore correctly state when hidden filters selected

---

src/glados/old_urls_redirector.py
src/glados/urls.py

This is to support more old orls. Another step towards https://github.com/chembl/GLaDOS/issues/1048

Urls redirection: create a function to handle report card redirects

---

src/glados/urls.py

This is for https://github.com/chembl/GLaDOS/issues/1075
And for https://github.com/chembl/GLaDOS/issues/1083

Do sarfaris redirections

---

src/glados/urls.py

This is for https://github.com/chembl/GLaDOS/issues/1098

Allow faq(s)? to redirect to frequently asked questions in gitbook

---

src/glados/settings.py

This facilitates https://github.com/chembl/GLaDOS/issues/1078 and should help with other processes that involve the nfs.

Set saved results dir in config file

---

src/glados/static/coffee/models/Activity.coffee

This is for https://github.com/chembl/GLaDOS/issues/1086

Fix browse activities item parsing

---

src/glados/static/coffee/views/Assay/AssayBasicInformationView.coffee
src/glados/templates/glados/AssayReportCardParts/BasicInformation.html

This is for https://github.com/chembl/GLaDOS/issues/1104

Assay Report Card: add puchemb source link when id exists

---

src/glados/api/chembl/dynamic_downloads/downloads_manager.py
src/glados/static/coffee/models/ServerSideDownloads/DownloadModel.coffee
src/glados/static/coffee/views/ServerSideDownloads/ServerSideDownloadView.coffee
src/glados/templates/glados/Handlebars/PreloaderSources.html
src/glados/templates/glados/SearchResultsParts/SearchBar.html
src/glados/urls.py
src/glados/utils/manage_downloads.py

Another step for https://github.com/chembl/GLaDOS/issues/1078

Inform download expiration time on the interface

---

src/glados/api/chembl/sssearch/structure.py

This should fix https://github.com/chembl/GLaDOS/issues/1117

Structure Search: Quote term to prevent errors with web services call.

---

src/glados/static/coffee/models/Assay.coffee
src/glados/static/coffee/views/Assay/AssayBasicInformationView.coffee
src/glados/templates/glados/AssayReportCardParts/BasicInformation.html

This is for https://github.com/chembl/GLaDOS/issues/1115

Add bindingdb links to assay rep card

---

src/glados/templates/glados/MainPageParts/Markup/json_ld.html
src/glados/views.py

Final step and bug fix for https://github.com/chembl/GLaDOS/issues/1082

Structured data: make sure jsonld is generated as a string

---

src/glados/api/chembl/dynamic_downloads/downloads_manager.py

Downloads: do not include compounds with empty structure ('' or None)

---

src/glados/static/coffee/compoundReportCardApp.coffee

This is for https://github.com/chembl/GLaDOS/issues/1132

Compound Report Card: Documents By Year, fix histogram year sorting

---

src/glados/static/coffee/views/ReportCards/MetabolismInCardView.coffee
src/glados/templates/glados/CompoundReportCardParts/Metabolism.html

This is for https://github.com/chembl/GLaDOS/issues/1004

Compound Report Card: fix link to metabolism full screen view

---

configurations/config_example.yml
configurations/minimal_dev_config.yml
src/glados/static/coffee/models/paginatedCollections/esSchema/FacetingHandler.coffee

Fix boolean facets 

---

src/glados/static/coffee/compoundReportCardApp.coffee

Show Mechanism of Action data for all compounds

---

src/glados/es/es_properties_configuration/config/groups.yml
src/glados/es/es_properties_configuration/config/override.yml
src/glados/static/coffee/apps/Embedding/EmbeddingApp.coffee
src/glados/static/coffee/assayReportCardApp.coffee
src/glados/static/coffee/models/Assay.coffee
src/glados/static/coffee/views/ReportCards/EntityDetailsInCardView.coffee
src/glados/templates/glados/AssayReportCardParts/AssayParameters.html
src/glados/templates/glados/assayReportCard.html
src/glados/templates/glados/compoundReportCard.html

This should close https://github.com/chembl/GLaDOS/issues/785

Add assay params and activity props

---

src/glados/es/es_properties_configuration/configuration_manager.py

It now prints 2 nice tab-separated tables.
It is accessible by 
```bash
./manage_glados_no_install.sh getpropertiescounts
```
Example output:
```bash
Groups Counts:
Index Name	Groups	Total Groups
chembl_target_component		0
chembl_tissue	download(default) browser_table(default, optional)	2
chembl_activity	download(default) browser_table(default, optional)	2
chembl_metabolism		0
chembl_drug_indication_by_parent	download(default) browser_table(default, optional)	2
chembl_cell_line	download(default) browser_table(default, optional)	2
chembl_biotherapeutic		0
chembl_drug		0
chembl_molecule_form		0
chembl_mechanism		0
chembl_assay	download(default) assay_parameters(default) browser_table(default, optional)	3
chembl_atc_class		0
chembl_target_relation		0
chembl_document_similarity		0 …
```

Upgrade properties counter

---

src/glados/static/coffee/views/PaginatedViews/PaginatedTable.coffee

Fix https://github.com/chembl/GLaDOS/issues/1171

Do not hide paginators or header when one page or one element

---

src/glados/es/es_properties_configuration/config/groups.yml
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/views/PaginatedViews/PaginatedViewBase.coffee

Fixes https://github.com/chembl/GLaDOS/issues/1172

Fix mechanism of action and drug indications in report cards

---

src/glados/es/es_properties_configuration/config/groups.yml

Resolves https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=359771

Assays: add confidence score and label to the possible columns

---

src/glados/static/coffee/SearchResultsApp.coffee
src/glados/static/coffee/models/Compound.coffee
src/glados/static/coffee/models/Compound/UnichemConnectivityMatch.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/models/paginatedCollections/SpecificFlavours/UnichemConnectivityRefsList.coffee
src/glados/static/scss/main_page_style.scss
src/glados/templates/glados/MainPageParts/about_chembl.html
src/glados/templates/glados/SearchResultsParts/SearchBar.html

-fix for #1193
-removal of ChEMBL@10 banner
-reinclusion of substructure highlighting 
-fix for similarity maps from beaker

Fix similarity maps and other updates

---

src/glados/static/coffee/views/Compound/MetabolismView.coffee

Compound Metabolism: Fix visualisation links (#1199)

---

src/glados/static/coffee/views/Compound/MetabolismView.coffee

This is for https://github.com/chembl/GLaDOS/issues/1036

Metabolism Visualisation: remove document from link info

---

src/glados/static/coffee/apps/Browsers/BrowserApp.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/models/Compound/Drug.coffee
src/glados/static/coffee/models/Compound/MechanismOfAction.coffee
src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionBase.coffee
src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
src/glados/static/coffee/models/paginatedCollections/Settings.coffee
src/glados/static/coffee/models/paginatedCollections/esSchema/CompoundSchema.coffee
src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee
src/glados/static/coffee/views/MainPage/ZoomableSunburstView.coffee
src/glados/static/scss/search_results_style.scss
src/glados/templates/glados/Handlebars/Browsers/BrowserSources.html

As requested by @anne123, @apbento and @agaulton

Tweak links to other entities

---

src/glados/static/coffee/TissueReportCardApp.coffee
src/glados/static/coffee/Utils.coffee
src/glados/static/coffee/assayReportCardApp.coffee
src/glados/static/coffee/cellLineReportCardApp.coffee
src/glados/static/coffee/compoundReportCardApp.coffee
src/glados/static/coffee/documentReportCardApp.coffee
src/glados/static/coffee/targetReportCardApp.coffee
src/glados/static/coffee/views/Visualisation/HistogramView.coffee
src/glados/static/coffee/views/Visualisation/PlotView.coffee
src/glados/static/scss/visualisations_style.scss
src/glados/templates/glados/base/Visualisation/DefaultHistogramContent.html
src/glados/templates/glados/compoundReportCard.html

Fixes https://github.com/chembl/GLaDOS/issues/1196

Make charts button more visible

---

src/glados/static/marvinjs/m4js

MarvinJS: update license

---

src/glados/static/coffee/views/Document/DocumentBasicInformationView.coffee
src/glados/static/coffee/views/References/ReferencesView.coffee
src/glados/templates/glados/DocumentReportCardParts/BasicInformation.html

Add these 2 simple fixes (for #1192 and #1192) out of the chembl26 branch, so we don't have to wait for the indexing and refactoring.

Cherrypick fixes to 1211 and 1192

---

src/glados/static/coffee/models/TargetComponent.coffee

Target Components: fix generation of accession link to ensembl
